kind = "mobile"
previewPath = "/"
title = "QRoams"
version = "1.0.0"
id = "artifacts/qromes"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
localPort = 25890
name = "expo"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/qromes run dev"

[services.env]
PORT = "25890"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/qromes", "run", "build"]
run = ["pnpm", "--filter", "@workspace/qromes", "run", "serve"]
